version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-golang-app
    container_name: my-golang-app
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    environment:
      API_KEY: ${API_KEY}
      API_URL: ${API_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_DATABASE: ${DB_DATABASE}
    depends_on:
      - db

  db:
    image: postgres
    container_name: ${DB_HOST}
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - ${DB_PORT}:${DB_PORT}
