version: '3.9'

services:
  #https://github.com/golang-migrate/migrate
  migration:
    image: migrate/migrate:4
    networks:
      - new
    volumes:
      - ./migrations/postgres:/migrations
    command: ["-path", "./migrations", "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@database:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up"]
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      -  ${DB_PORT}:${DB_PORT}
    networks:
      new:
        aliases:
            - database
    healthcheck:
      test: ["CMD","pg_isready", "-h", "localhost" ,"-p", "${DB_PORT}"]
      interval: 3s
      timeout: 2s
      retries: 5

networks:
      new: