version: '3.8'

services:
  db:
    image: postgres:15
    container_name: pg_database
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    healthcheck:
      test: [ "CMD","pg_isready", "-U","${DB_USERNAME}", "-h", "localhost" ,"-p", "${DB_PORT}" ]
      interval: 3s
      timeout: 2s
      retries: 5
    ports:
      - ${DB_PORT}:${DB_PORT}

  #https://github.com/golang-migrate/migrate
  migration:
    image: migrate/migrate:4
    container_name: migration_service
    env_file:
      - .env
    volumes:
      - ./assets/migrations/postgres/:/migrations
    command: [ "-path", "./migrations", "-database", "postgres://${DB_USERNAME}:${DB_PASSWORD}@db:${DB_PORT}/${DB_DATABASE}?sslmode=disable", "up", "2" ]
    depends_on:
      db:
        condition: service_healthy